//
//  StringConstant.swift
//  pummel
//
//  Created by Bear Daddy on 10/28/16.
//  Copyright © 2016 pummel. All rights reserved.
//

import Foundation

// String Code
let widthHeight80 = "?width=80&height=80"
let widthHeight120 = "?width=120&height=120"
let widthHeight160 = "?width=160&height=160"
let widthHeight320 = "?width=320&height=320"
let widthHeight640 = "?width=640&height=640"
let widthHeight250 = "?width=250&height=250"
let widthHeight100 = "?width=100&height=100"
let widthHeight200 = "?width=200&height=200"
let widthHeight236 = "?width=236&height=236"
let widthEqual = "?width="
let heighEqual = "&height="

// Alert
let pmmNotice = "Oops"
let couldNotSendEmailAlert = "Your device could not send e-mail. Please check e-mail configuration and try again."
let pleaseDoItAgain = "Please do it again"
let yourEmailIsNotValid = "The email address you have entered is already registered"
let openLink = "Pummel app will open a link in safari"
let pleaseInputADate = "Please input a date"
let pummelSlogan = "Find a personal trainer or fitness expert in your area, download the app now! https://appsto.re/i67V7vG"
let sendAFeedback = "Send a feedback"
let letAddYourDetail = "Let's add your detail"
let pleaseChoosePngOrJpeg =  "Please choose jpeg or png file"
let imageJpeg = "image/jpeg"
let imagePng = "image/png"
let jpgeFile = "imagefile.jpeg"
let pngFile = "imagefile.png"
let pleaseCheckYourInformationAgain = "Some information couldnt update. Please check your information again"
let sendYouAImage = "Sent you a image"
let sendYouAVideo = "Sent you a video"
let addAComment =  "ADD A COMMENT..."
let accessRequested = "Access Requested"
let savingImageNeedsToAccessYourPhotoAlbum = "Saving image needs to access your photo album"
let passwordNotice = "Please try a combination of numbers and letters"
let signInNotice = "Please check email and password"
let registerNoticeSuccessWithoutImage = "Resgister sucessfully, but image profile isn't updated, let do it later"
let registerNoticeSuccessButCantSignAutomatic =  "Register sucessfully, but can't sign it automatically. Please sign in again"
let cookieExpiredNotice = "Your cookie was expired, please go to setting to logout and login again"
let turnOneLocationServiceApp = "Pummel need location service to search. Please go to Setting -> Pummel -> Turn on location service"
let turnOneLocationServiceSystem = "Pummel need location service to search. Please go to Setting -> Priavcy -> Turn on location service"
let addThisTagToDatabase = "Are you going add this tag to your specialties?"
let linkInvalid = "Your link isn’t valid!"
let confirmChangedLocation = "You have already changed the service area."
let contactExist = "This coach has already added to your contact"
let metric = "Metric"
let imperial = "Imperial"
let passWordMinCharacter = "Password must have at least 8 characters. Please try a combination of letters and words."
let passWordNotMatch = "New password does not match with retype new password"
let curPassWrong = "Current password does not match, please retype"
let notfindPhoto = "This post is no longer available"
// Key String
let k_PM_3D_TOUCH = "3DTouch"
let k_PM_3D_TOUCH_VALUE = "3DTouch_Default_Value"
let k_PM_3D_TOUCH_NOTIFICATION = "3DTouchNotification"
let k_PM_IS_LOGINED = "isLogined"
let k_PM_IS_COACH = "isCoach"
let k_PM_CURRENT_ID = "currentId"
let k_PM_PUSH_TOKEN = "pushToken"
let k_PM_URL_LAST_COOKIE = "urlLastCookie"
let k_PM_HEADER_FILEDS = "headerFields"
let k_PM_SHOW_BADGE = "showBadge"
let k_PM_SELECTED_NOTIFI = "selectedNotify"
let k_PM_REFRESH_MESSAGE = "refreshMessage"
let k_PM_IS_UP_COMING = "isUpComing"
let k_PM_UPDATE_SESSION_NOTIFICATION = "updateSessionNotification"

// Key Json
let kConversationId = "conversationId"
let kServiceArea = "serviceArea"
let kLevel = "level"
let kDistance = "distance"
let kState = "state"
let kCity = "city"
let kImageUrl = "imageUrl"
let kRating = "rating"
let kConnectionCount = "connectionCount"
let kPostCount = "postCount"
let kUser = "user"
let kUserId = "userId"
let kCoachId = "coachId"
let kUnits = "units"
let kProfilePic = "profilePic"
let kBio = "bio"
let kLastName = "lastname"
let kFirstname = "firstname"
let kGender = "gender"
let kEmail = "email"
let kDob = "dob"
let kHeight = "height"
let kWeight = "weight"
let kMobile = "mobile"
let kText = "text"
let KVideoUrl = "videoUrl"
let kConversation = "conversation"
let kConversationUser = "conversationUsers"
let kLastOpenAt = "lastOpenedAt"
let kId = "id"
let kUserIds = "userIds"
let kPassword = "password"
let kPasswordNew = "passwordNew"
let kProtocol = "protocol"
let kToken = "token"
let kDontCare = "Dont care"
let kTags = "tags"
let kTitle = "title"
let kInstagramUrl = "instagramUrl"
let kFacebookUrl = "facebookUrl"
let kTwitterUrl = "twitterUrl"
let kAchievement = "achievements"
let kWebsiteUrl = "websiteUrl"
let kQualification = "qualifications"
let kCreateAt = "createdAt"
let kCount = "count"
let kPostId = "postId"
let kBusinessId = "businessId"
let kLat = "lat"
let kLong = "long"
let kLimit = "limit"
let kOffset = "offset"
let kEmergencyName = "emergencyName"
let kEmergencyMobile = "emergencyMobile"
let kType = "type"
let kIntensity = "intensity"
let kLongtime = "longtime"
let kCalorie = "calorie"
let kDatetime = "datetime"
let kUserIdTarget = "userIdTarget"
let kUserIdRequest = "userIdRequest"
let kActivityId = "activityId"
let kCoach = "coach"

// String
let kLogoutSuccess = "Logout successful"
let kCancle = "Cancel"
let kOk = "OK"
let kDone = "DONE"
let kApplyNow = "APPLY NOW"
let kSweetThanks = "SWEET, THANKS!"
let kReportAProblem = "Report a problem"
let kSendaFeedback = "Send a feedback"
let k25kms = "25kms"
let kSelectFromLibrary = "Select From Library"
let kAddToIphoneContact = "Add to Your Contact"
let kViewProfile = "View Profile"
let kShareTo = "Share"
let kSetToCurrentCustomer = "Set to Current Trainee"
let kMoveToOld = "Move To Old Group"
let kMoveToCurrent = "Move To Old Group"
let kTakePhoto = "Take Photo"
let kEmailRegEx = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
let kDateFormat = "YYYY-DD-mm"
let kFullDateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
let kMale = "Male"
let kFemale = "Female"
let kMALEU = "MALE"
let kFemaleU = "FEMALE"
let kGYM = "GYM"
let kSMALLGROUPTRAINING = "SMALL GROUP TRAINING"
let kBOOTCAMP = "BOOTCAMP"
let kMOBILE = "MOBILE"
let kOUTDOOR = "OUTDOOR"
let kPRIVATESTUDIO = "PRIVATE STUDIO"
let kANYWHERE = "ANYWHERE"
let kDontCareUp = "DON'T CARE"
let kShare = "Share"
let KReport = "Report"
let kRows = "rows"
let kBook = "Book"
let kLog = "Log"
let kContinue = "Continue"
let kNext = "Next"
let kSave = "Save"
let kEdit = "Edit"
let kInvite = "Invite"
let kSession = "SESSIONS"
let kThanks = "Thanks"
let kMessageUpgradedCoach = "Thanks for your Pummel Fitness coach application, we will review this shortly and get back to you"

// Button
let kNavSetting = "SETTINGS"
let kNavProfile = "PROFILE"
let kNavEditProfile = "EDIT PROFILE"
let kNavSession = "SESSIONS"
let kLogSession = "LOG SESSION"
let kNavMessage = "MESSAGES"
let kNavNewMessage = "NEW MESSAGE"
let kNavSendPhoto = "SEND PHOTO"
let kNavFeed = "FEED"
let kNavPost = "POST"
let kBookSession = "BOOK SESSION"
let kBookShare = "SHARE"
let kClients = "CLIENTS"
let kCoaches = "COACHES"
let kChangePassword = "CHANGE PASSWORD"

// Cell
let kSettingDiscoveryHeaderTableViewCell = "SettingDiscoveryHeaderTableViewCell"
let kSettingLocationTableViewCell = "SettingLocationTableViewCell"
let kSettingMaxDistanceTableViewCell = "SettingMaxDistanceTableViewCell"
let kSettingNewConnectionsTableViewCell = "SettingNewConnectionsTableViewCell"
let kSettingNotificationHeaderTableViewCell = "SettingNotificationHeaderTableViewCell"
let kSettingHelpSupportTableViewCell = "SettingHelpSupportTableViewCell"
let kSettingSmallSeperateTableViewCell = "SettingSmallSeperateTableViewCell"
let kSettingLogoutTableViewCell = "SettingLogoutTableViewCell"
let kSettingBigSeperateTableViewCell = "SettingBigSeperateTableViewCell"

let kAboutCollectionViewCell = "AboutCollectionViewCell"
let kMessageTableViewCell = "MessageTableViewCell"

let kUserTableViewCell = "UserTableViewCell"
let kChatMessageHeaderTableViewCell = "ChatMessageHeaderTableViewCell"
let kChatMessageWithoutImageTableViewCell = "ChatMessageWithoutImageTableViewCell"
let kChatMessageImageTableViewCell = "ChatMessageImageTableViewCell"

let kTagCell = "TagCell"
let kFeaturedFeedTableViewCell = "FeaturedFeedTableViewCell"

let kFeedFirstPartTableViewCell = "FeedFirstPartTableViewCell"
let kFeedSecondPartTableViewCell = "FeedSecondPartTableViewCell"
let kFeedThirdPartTableViewCell = "FeedThirdPartTableViewCell"
let kFeedFourthPartTableViewCell = "FeedFourthPartTableViewCell"

let kActivityCell = "ActivityCell"

// Profile
let kIAmFitnessProfessional = "I’M A FITNESS PROFESSIONAL"
let kVerifiedFitnessProfessional = "Would you like to become a verified Pummel Fitness professional?  Fill in this form to setup your Mobile profile and start finding new customers."
let kUnitMeasure = "UNITS OF MEASURE"
let kNotification = "NOTIFICATIONS"
let kNewConnections = "New Leads"
let kMessage = "MESSAGES"
let kSessions = "SESSIONS"
let kContactUs = "CONTACT US"
let kHelpSupport = "HELP & SUPPORT"
let kFeedback = "FEEDBACK"
let kSharePummel = "SHARE PUMMEL"
let kLegal = "LEGAL"
let kPrivacy = "PRIVACY POLICY"
let kTermOfService = "TERMS OF SERVICE"
let kUnit = "UNIT"

// Navigation 
let kGoConnect = "goConnect"
let kGoProfile = "goProfile"
let kGoUserProfile = "goUserProfile"
let kSendMessageConnection = "sendMessageConnection"


// Seting
let kApply = "Apply"
let kWantToBecomeACoach = "Please click continue to fill in your application to become a Pummel fitness coach."
let kBecomeACoachSuccess = "You have accepted to become a Trainer. Let's go to profile to edit your infomation"
let kMessConfirmLogout = "Are you sure you want to log out?"
let kMessageInviteContact = "Find a personal trainer or fitness expert in your area, download the app now! https://appsto.re/i67V7vG http://pummel.fit"
