//
//  StringConstant.swift
//  pummel
//
//  Created by Bear Daddy on 10/28/16.
//  Copyright © 2016 pummel. All rights reserved.
//

import Foundation

// String Code
let widthHeight80 = "?width=80&height=80"
let widthHeight120 = "?width=120&height=120"
let widthHeight160 = "?width=160&height=160"
let widthHeight320 = "?width=320&height=320"
let widthHeight250 = "?width=250&height=250"
let widthHeight100 = "?width=100&height=100"
let widthHeight200 = "?width=200&height=200"
let widthHeight236 = "?width=236&height=236"
let widthEqual = "?width="
let heighEqual = "&height="

// Alert
let pmmNotice = "PM Notice"
let couldNotSendEmailAlert = "Your device could not send e-mail. Please check e-mail configuration and try again."
let pleaseDoItAgain = "Please do it again"
let pummelSlogan = "Find a personal trainer or fitness expert in your area"
let sendAFeedback = "Send a feedback"
let letAddYourDetail = "Let's add your detail"
let pleaseChoosePngOrJpeg =  "Please choose jpeg or png file"
let imageJpeg = "image/jpeg"
let imagePng = "image/png"
let jpgeFile = "imagefile.jpeg"
let pngFile = "imagefile.png"
let thisIsYourBio = "This is your bio"
let thisIsYourMobile = "This is your mobile"
let pleaseCheckYourInformationAgain = "Please check your information again"
let sendYouAImage = "Sent you a image"
let sendYouAVideo = "Sent you a video"
let addAComment =  "ADD A COMMENT..."
let accessRequested = "Access Requested"
let savingImageNeedsToAccessYourPhotoAlbum = "Saving image needs to access your photo album"
let passwordNotice = "Please try a combination of numbers and letters"
let signInNotice = "Please check email and password"
let registerNoticeSuccessWithoutImage = "Resgister sucessfully, but image profile isn't updated, let do it later"
let registerNoticeSuccessButCantSignAutomatic =  "Register sucessfully, but can't sign it automatically. Please sign in again"
let cookieExpiredNotice = "Your cookie was expired, please go to setting to logout and login again"
// Key String
let k_PM_IS_LOGINED = "isLogined"
let k_PM_IS_COACH = "isCoach"
let k_PM_CURRENT_ID = "currentId"
let k_PM_PUSH_TOKEN = "pushToken"
let k_PM_URL_LAST_COOKIE = "urlLastCookie"
let k_PM_HEADER_FILEDS = "headerFields"
let k_PM_SHOW_BADGE = "showBadge"
let k_PM_SELECTED_NOTIFI = "selectedNotify"
let k_PM_REFRESH_MESSAGE = "refreshMessage"
// Key Json
let kConversationId = "conversationId"
let kServiceArea = "serviceArea"
let kLevel = "level"
let kDistance = "distance"
let kImageUrl = "imageUrl"
let kRating = "rating"
let kConnectionCount = "connectionCount"
let kPostCount = "postCount"
let kUser = "user"
let kUserId = "userId"
let kProfilePic = "profilePic"
let kBio = "bio"
let kLastName = "lastname"
let kFirstname = "firstname"
let kGender = "gender"
let kEmail = "email"
let kDob = "dob"
let kMobile = "mobile"
let kText = "text"
let KVideoUrl = "videoUrl"
let kConversation = "conversation"
let kConversationUser = "conversationUsers"
let kLastOpenAt = "lastOpenedAt"
let kId = "id"
let kUserIds = "userIds"
let kPassword = "password"
let kProtocol = "protocol"
let kToken = "token"
let kDontCare = "Dont care"
let kTags = "tags"
let kTitle = "title"
let kInstagramUrl = "instagramUrl"
let kFacebookUrl = "facebookUrl"
let kTwitterUrl = "twitterUrl"
let kAchievement = "achievements"
let kWebsiteUrl = "websiteUrl"
let kQualification = "qualifications"
let kCreateAt = "createdAt"
let kCount = "count"
let kPostId = "postId"
let kBusinessId = "businessId"

// String
let kLogoutSuccess = "Logout successful"
let kCancle = "Cancel"
let kOk = "OK"
let kDone = "DONE"
let kReportAProblem = "Report a problem"
let kSendaFeedback = "Send a feedback"
let k25kms = "25kms"
let kSelectFromLibrary = "Select From Library"
let kTakePhoto = "Take Photo"
let kEmailRegEx = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
let kDateFormat = "YYYY-DD-mm"
let kFullDateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
let kMale = "Male"
let kFemale = "Female"
let kMALEU = "MALE"
let kFemaleU = "FEMALE"
let kGYM = "GYM"
let kSMALLGROUPTRAINING = "SMALL GROUP TRAINING"
let kBOOTCAMP = "BOOTCAMP"
let kMOBILE = "MOBILE"
let kOUTDOOR = "OUTDOOR"
let kPRIVATESTUDIO = "PRIVATE STUDIO"
let kANYWHERE = "ANYWHERE"
let kDontCareUp = "DON'T CARE"
let kShare = "Share"
let KReport = "Report"
let kRows = "rows"
// Button 
let kNavSetting = "SETTINGS"
let kNavProfile = "PROFILE"
let kNavEditProfile = "EDIT PROFILE"
let kNavSession = "SESSIONS"
let kNavMessage = "MESSAGES"
let kNavNewMessage = "NEW MESSAGE"
let kNavSendPhoto = "SEND PHOTO"
let kNavFeed = "FEED"
let kNavPost = "POST"

// Cell
let kSettingDiscoveryHeaderTableViewCell = "SettingDiscoveryHeaderTableViewCell"
let kSettingLocationTableViewCell = "SettingLocationTableViewCell"
let kSettingMaxDistanceTableViewCell = "SettingMaxDistanceTableViewCell"
let kSettingNewConnectionsTableViewCell = "SettingNewConnectionsTableViewCell"
let kSettingNotificationHeaderTableViewCell = "SettingNotificationHeaderTableViewCell"
let kSettingHelpSupportTableViewCell = "SettingHelpSupportTableViewCell"
let kSettingSmallSeperateTableViewCell = "SettingSmallSeperateTableViewCell"
let kSettingLogoutTableViewCell = "SettingLogoutTableViewCell"
let kSettingBigSeperateTableViewCell = "SettingBigSeperateTableViewCell"

let kAboutCollectionViewCell = "AboutCollectionViewCell"
let kMessageTableViewCell = "MessageTableViewCell"

let kUserTableViewCell = "UserTableViewCell"
let kChatMessageHeaderTableViewCell = "ChatMessageHeaderTableViewCell"
let kChatMessageWithoutImageTableViewCell = "ChatMessageWithoutImageTableViewCell"
let kChatMessageImageTableViewCell = "ChatMessageImageTableViewCell"

let kTagCell = "TagCell"
let kFeaturedFeedTableViewCell = "FeaturedFeedTableViewCell"

let kFeedFirstPartTableViewCell = "FeedFirstPartTableViewCell"
let kFeedSecondPartTableViewCell = "FeedSecondPartTableViewCell"
let kFeedThirdPartTableViewCell = "FeedThirdPartTableViewCell"
let kFeedFourthPartTableViewCell = "FeedFourthPartTableViewCell"

// Profile
let kNotification = "NOTIFICATIONS"
let kNewConnections = "NEW CONNECTIONS"
let kMessage = "MESSAGES"
let kSessions = "SESSIONS"
let kContactUs = "CONTACT US"
let kHelpSupport = "HELP & SUPPORT"
let kFeedback = "FEEDBACK"
let kSharePummel = "SHARE PUMMEL"
let kLegal = "LEGAL"
let kPrivacy = "PRIVACY POLICY"
let kTermOfService = "TERMS OF SERVICE"

// Navigation 
let kGoConnect = "goConnect"
let kGoProfile = "goProfile"
let kGoUserProfile = "goUserProfile"
let kSendMessageConnection = "sendMessageConnection"

