//
//  URLConstant.swift
//  pummel
//
//  Created by Bear Daddy on 10/28/16.
//  Copyright © 2016 pummel. All rights reserved.
//

import Foundation

let kPMAPI = "http://api.pummel.fit"
let kPMAPIUSER = "http://api.pummel.fit/api/users/"
let kPMAPISEARCHUSER = "http://api.pummel.fit/api/users/searchUser?offset="
let kPMAPICHECKUSERCONNECT = "http://api.pummel.fit/api/users/check"
let kPMAPIUSER_OFFSET = "http://api.pummel.fit/api/users?offset="
let kPMAPICOACH = "http://api.pummel.fit/api/coaches/"
let kPMAPICOACH_SEARCHV1 = "http://api.pummel.fit/api/coaches/search"
let kPMAPICOACH_SEARCH = "http://api.pummel.fit/api/coaches/searchdistanceV2"
let kPMAPI_LOGOUT = "http://api.pummel.fit/api/logout"
let kPMAPI_LIKE = "http://api.pummel.fit/api/likes/"
let kPMAPI_POST = "http://api.pummel.fit/api/posts/"
let kPMAPI_POST_OFFSET = "http://api.pummel.fit/api/posts/?offset="
let kPMAPI_LOGIN = "http://api.pummel.fit/api/login"
let kPMAPI_REPORT = "http://api.pummel.fit/api/posts/report"
let kPMAPI_FORGOT = "http://api.pummel.fit/api/forget"
let kPMAPI_REGISTER = "http://api.pummel.fit/api/register"
let kPMAPI_TAG_OFFSET = "http://api.pummel.fit/api/tags?offset="
let kPMAPI_TAG4_OFFSET = "http://api.pummel.fit/api/tags4?offset="
let kPMAPI_TAGALL_OFFSET = "http://api.pummel.fit/api/tagsAll?offset="
let kPMAPI_BUSINESS = "http://api.pummel.fit//api/businesses/"
let kPM_TERM = "http://pummel.fit/terms/"
let kPM_PRIVACY = "http://pummel.fit/privacy/"
let kPM = "http://pummel.fit"
let kPMAPIDELETEACTIVITY = "http://api.pummel.fit/api/activities/deleteActivity"
let kPMAPIACTIVITY = "http://api.pummel.fit/api/activities/"
let kPMSUPPORT_EMAIL = "support@pummel.fit"
let kPMHELLO_EMAIL = "hello@pummel.fit"
let kPM_PATH_PHOTO_PROFILE = "/photos"
let kPM_PATH_PHOTO = "/photos?offset="
let kPM_PATH_PHOTOV2 = "/photosV2?offset="
let kPM_PATH_CONVERSATION = "/conversations"
let kPM_PATH_CONVERSATION_OFFSET = "/conversations?offset="
let kPM_PATH_DEVICES =  "/devices"
let kPM_PARTH_MESSAGE = "/messages"
let kPM_PATH_LIKE = "/likes"
let kPM_PATH_COMMENT_OFFSET = "/comments?offset="
let kPM_PATH_COMMENT_LIMIT = "/comments?limit="
let kPM_PATH_LIMIT_ONE = "&limit=1"
let kPM_PATH_LOG_ACTIVITIES_USER = "/activitiesuserV2"
let kPM_PATH_LOG_ACTIVITIES_COACH = "/activitiescoachV2"
let kPM_PATH_ACTIVITIES_USER = "/activitiesuser?offset="
let kPMAPI_ADD_TAG = "http://api.pummel.fit/api/tags"
let kPMAPICOACH_LEADS = "/leads?offset="
let kPMAPICOACH_CURRENT = "/current?offset="
let kPMAPICOACH_OLD = "/old?offset="
let kPMAPICOACH_JUSTCONNECTED = "/justconnected?offset="
let kPMAPICOACH_COACHCURRENT = "/currentCoach?offset="
let kPMAPICOACH_COACHOLD = "/pastCoach?offset="
let kPMAPICOACHES = "http://api.pummel.fit/api/coaches/"
let kPMAPICOACH_BOOK = "/bookV2"
let kPMAPI_LEAD = "/lead"
let kPMAPI_CHANGEPASS = "/password"
let kPMAPI_POSTOFPHOTO = "/api/postOfPhoto"
